# Site settings
title: RackHD
email: your-email@domain.com
url: https://rackhd.github.io
description: "RackHD HomePage: RackHD is a technology stack for enabling automated hardware management and orchestration through cohesive APIs."
skills: "Hardware Management and Orchestration"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 202331 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 292c3b #FD6E8A
  secondary-dark: 191b28 #A2122F
  focus: ffffff #bdb76b
  grad: 444654 
  title: d9d9d9

# Footer settings
footer:
  copyright:
  #location: Location
  social:  Keep In Touch
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rackhd 
  - title: group
    url: https://groups.google.com/forum/#!forum/rackhd 
  - title: github
    url: https://github.com/RackHD 
  - title: slack
    url: https://codecommunity.slack.com/archives/rackhd 

# Postal address (add as many lines as necessary)
#address:
#  - line: Dell EMC, 176 South St
#  - line: Hopkinton, MA 01748

# Credits content
#credits: 'find RackHD at <a>github.com/rackhd</a> '

# Build settings
markdown: kramdown
permalink: pretty
